services
  - type web
    name smart-business-pro
    runtime python
    buildCommand pip install -r requirements.txt
    startCommand gunicorn appapp
    envVars
      - key PYTHON_VERSION
        value 3.11.0
      - key SECRET_KEY
        generateValue true